# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/include -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/drivers/input/misc

ldc2114_keys-objs := ldc2114.o

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    # Following line is in control of extra debug
    EXTRA_CFLAGS += -DLDC2114_POLL_DEBUG -DLDC2114_CFG_DEBUG #-DLDC2114_CHARDEV
    #ldc2114_keys-objs += ldc2114-cdev.o
endif

obj-m = ldc2114_keys.o
