# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/include

ifeq ($(filter m y, $(CONFIG_INPUT_DRV2624_HAPTICS)),)
obj-m += drv2624_mmi.o
endif
