# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/include \
		-I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/drivers/power/mmi_pl_chg_manager

obj-m += mmi_pl_chg_manager.o
