# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/include \
		-I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/drivers/power/bq2597x_mmi

obj-m += bq2597x_mmi.o
