# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/include \
		-I$(TOP)/$(KERNEL_SOURCE_PATH)/modules/drivers/input/touchscreen/raydium_mmi

obj-m := raydium_mmi.o
raydium_mmi-objs += raydium_i2c_ts.o
